// <auto-generated />
#pragma warning disable CA1062, CA1014, CA1308, CA1305, CA1707, CA1816, CA1819, CA1825
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Moongazing.OrionShowcase.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class EncryptedColumnsToBytea : Migration
    {
        // The customer email / phone / national_id columns were originally scaffolded as text (the
        // OrionVault model customizer that rewrites them to byte[] does not run at design time), so
        // the values were written as plaintext and OrionVault's string->byte[] encryption never
        // applied. These ALTERs move them to bytea so the EncryptedStringConverter (and the composed
        // Tckn->string->byte[] converter for national_id) actually encrypts at rest.
        //
        // PostgreSQL has no implicit/assignment cast between text and bytea, so ALTER COLUMN ... TYPE
        // bytea is rejected at plan time WITHOUT an explicit USING clause - even on an empty table.
        // EF's AlterColumn does not emit USING, so these are raw statements. convert_to(value, 'UTF8')
        // is the canonical text->bytea conversion; the per-test databases are created fresh and empty,
        // so the conversion only has to be valid SQL, never preserve real data.

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                "ALTER TABLE customers ALTER COLUMN phone TYPE bytea USING convert_to(phone, 'UTF8');");
            migrationBuilder.Sql(
                "ALTER TABLE customers ALTER COLUMN national_id TYPE bytea USING convert_to(national_id, 'UTF8');");
            migrationBuilder.Sql(
                "ALTER TABLE customers ALTER COLUMN email TYPE bytea USING convert_to(email, 'UTF8');");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // bytea->text likewise needs an explicit USING; convert_from is the inverse of convert_to.
            migrationBuilder.Sql(
                "ALTER TABLE customers ALTER COLUMN phone TYPE text USING convert_from(phone, 'UTF8');");
            migrationBuilder.Sql(
                "ALTER TABLE customers ALTER COLUMN national_id TYPE text USING convert_from(national_id, 'UTF8');");
            migrationBuilder.Sql(
                "ALTER TABLE customers ALTER COLUMN email TYPE text USING convert_from(email, 'UTF8');");
        }
    }
}
