// <auto-generated />
#pragma warning disable CA1062, CA1014, CA1308, CA1305, CA1707, CA1816, CA1819, CA1825
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Moongazing.OrionShowcase.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddOutboxDeadLetterAndArchive : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "orion_patch_dead_letter",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    message_type = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    payload = table.Column<string>(type: "text", nullable: false),
                    headers_json = table.Column<string>(type: "text", nullable: true),
                    correlation_id = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    occurred_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    enqueued_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    attempt_count = table.Column<int>(type: "integer", nullable: false),
                    final_error = table.Column<string>(type: "text", nullable: false),
                    dead_lettered_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_orion_patch_dead_letter", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "orion_patch_outbox_archive",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    message_type = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: false),
                    payload = table.Column<string>(type: "text", nullable: false),
                    headers_json = table.Column<string>(type: "text", nullable: true),
                    correlation_id = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    occurred_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    enqueued_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    attempt_count = table.Column<int>(type: "integer", nullable: false),
                    last_error = table.Column<string>(type: "text", nullable: true),
                    processed_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    archived_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_orion_patch_outbox_archive", x => x.id);
                });

            migrationBuilder.CreateIndex(
                name: "ix_orion_patch_dead_letter_dead_lettered_at",
                table: "orion_patch_dead_letter",
                column: "dead_lettered_at_utc");

            migrationBuilder.CreateIndex(
                name: "ix_orion_patch_outbox_archive_processed_at",
                table: "orion_patch_outbox_archive",
                column: "processed_at_utc");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "orion_patch_dead_letter");

            migrationBuilder.DropTable(
                name: "orion_patch_outbox_archive");
        }
    }
}
