// <auto-generated />
#pragma warning disable CA1062, CA1014, CA1308, CA1305, CA1707, CA1816, CA1819, CA1825
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Moongazing.OrionShowcase.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddNationalIdBlindIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "EntityBaseType",
                table: "OrionAudit_Log",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "EntityBaseType",
                table: "OrionAudit_Capture_Queue",
                type: "character varying(512)",
                maxLength: 512,
                nullable: true);

            // Added to an already-populated table, so the column is NULLABLE: existing customers
            // keep a null blind index until a production deployment backfills them by recomputing
            // the OrionVault blind index for each pre-existing national id. The unique FILTERED
            // index below excludes those null rows, so the missing backfill is safe and uniqueness
            // is still enforced for every newly registered customer.
            migrationBuilder.AddColumn<byte[]>(
                name: "national_id_index",
                table: "customers",
                type: "bytea",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "OrionPatch_Inbox",
                columns: table => new
                {
                    MessageId = table.Column<Guid>(type: "uuid", nullable: false),
                    Consumer = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    AcceptedAtUtc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_OrionPatch_Inbox", x => new { x.MessageId, x.Consumer });
                });

            // UNIQUE FILTERED index: enforces national-id uniqueness at the database level so two
            // concurrent registrations cannot both insert the same national id even if they race
            // past the async uniqueness validator. The "IS NOT NULL" filter keeps legacy rows with
            // a null (not-yet-backfilled) blind index out of the uniqueness constraint.
            migrationBuilder.CreateIndex(
                name: "ix_customers_national_id_index",
                table: "customers",
                column: "national_id_index",
                unique: true,
                filter: "national_id_index IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "OrionPatch_Inbox");

            migrationBuilder.DropIndex(
                name: "ix_customers_national_id_index",
                table: "customers");

            migrationBuilder.DropColumn(
                name: "EntityBaseType",
                table: "OrionAudit_Log");

            migrationBuilder.DropColumn(
                name: "EntityBaseType",
                table: "OrionAudit_Capture_Queue");

            migrationBuilder.DropColumn(
                name: "national_id_index",
                table: "customers");
        }
    }
}
